---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Jeff Spaulding"
keywords:    "jeff spaulding, resume, jekyll, linkedin"
description: "A resume website for Jeff Spaulding."
source_link: "https://github.com/t413/SinglePaged"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
### colors from materialuicolors.com, level 500 ###
colors:
  black:       '#111111'
  white:       '#f8f8f8'
  red:         '#F44336'
  pink:        '#E91E63'
  purple:      '#9C27B0'
  deeppurple: '#673AB7'
  indigo:      '#3F51B5'
  blue:        '#2196F3'
  lightblue:  '#03A9F4'
  cyan:        '#00BCD4'
  teal:        '#009688'
  green:       '#4CAF50'
  lightgreen: '#8BC34A'
  lime:        '#CDDC39'
  yellow:      '#FFEB3B'
  amber:       '#FFC107'
  orange:      '#FF9800'
  deeporange: '#FF5722'
  brown:       '#795548'
  grey:        '#9E9E9E'
  bluegrey:   '#607D8B'

kramdown:
  auto_ids:  false

